source 'http://rubygems.org'

gem 'sinatra'
gem 'pg'
gem 'sinatra-activerecord'
gem 'sinatra-reloader'
gem 'pry'
gem 'bcrypt'
gem 'dotenv'
gem 'json'
gem 'thin'
gem 'twitter'
gem 'capybara'
gem 'mongo'
gem 'bson_ext'